### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by ghost** [Ochii/cso2-master-services#39]
https://youtu.be/EdynrUzTBeI

Has the installation method changed?

**Comment by dounai2333** [comment]
if you encounter any problems, do not use the ps1 setup script, go download everything manually:
[gulpjs](https://gulpjs.com/), [MongoDB](https://www.mongodb.com/), [cso2-master-server](https://github.com/L-Leite/cso2-master-server/), [cso2-user-services](https://github.com/L-Leite/cso2-users-service), [cso2-webapp](https://github.com/L-Leite/cso2-webapp/)
(cso2-inventory-service has been abandoned, you don't need it anymore)

make sure MongoDB is ready, and you can use "gulp" on the cmd or ps1 console, then run "npm install" and "gulp build" on every project.
after install in done, change the value in the ps1 start script, then run server with it, everything should be fine

MongoDB setup command if you need:
--bind_ip "127.0.0.1" --port 30099 --dbpath "db"

after run the server, you should see 4 consoles: (MongoDB, user-services, webapp, master-server)
![7J5_NNWYL{U{U64U%HXF)_Y](https://user-images.githubusercontent.com/45044404/82973153-44f0c100-a009-11ea-90b7-5151cb0b4fd1.png)

**Comment by ExplosionMagicMegumin** [comment]
[root@localhost users-service]# gulp build
[22:56:42] Using gulpfile /home/nodejs/server/users-service/gulpfile.js
[22:56:42] Starting 'build'...
[22:56:42] Starting 'clean:dist'...
[22:56:42] Cleaning transpiled source...
[22:56:42] Finished 'clean:dist' after 42 ms
[22:56:42] Starting 'tslint'...
[22:56:42] Linting source code...
[22:56:44] Finished 'tslint' after 1.37 s
[22:56:44] Starting 'typescript'...
[22:56:44] Transpiling source code...
src/entities/inventory/inventory.ts(102,76): error TS2322: Type 'number' is not assignable to type 'Partial<InventoryItem> | { itemId?: QuerySelector<number>; ammount?: QuerySelector<number>; }'.
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
[22:56:54] 'typescript' errored after 11 s
[22:56:54] Error: TypeScript: Compilation failed
    at Output.mightFinish (/home/nodejs/server/users-service/node_modules/gulp-typescript/release/output.js:130:43)
    at applySourceMap.then.appliedSourceMap (/home/nodejs/server/users-service/node_modules/gulp-typescript/release/output.js:43:22)
[22:56:54] 'build' errored after 12 s
[root@localhost users-service]#

**Comment by ExplosionMagicMegumin** [comment]
could you please send me one built?

I built the master server smoothly
user gives error while building service

**Comment by ExplosionMagicMegumin** [comment]
[Server_Start.txt](https://github.com/L-Leite/cso2-master-services/files/4840947/Server_Start.txt)

I use this to start the server

**Comment by ExplosionMagicMegumin** [comment]
@dounai2333
